# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aftercare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aftercare
  
  pod 'Alamofire', '~> 4.4'
  
  target 'AftercareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AftercareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
